### ISSUE TITLE
Multiple build not supported

### ISSUE THREAD

**Issue by jesserockz** [Arvernus/Shelly-for-ESPHome#4]
Hi @jowgn 

The workflow does not yet support building different firmware for different devices, only the same firmware for different chips, ESP32 & ESP8266 etc.

I am actually working on a multi-build branch that would allow this but was having some trouble when I got busy on other things. (see https://github.com/jesserockz/sonoff-configs which is not quite there yet.)

**Comment by jowgn** [comment]
@jesserockz I think I got a first version working here. Fell free to copy stuff is interested.
